services:
  - type: web
    name: inventory-management
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt 
      python manage.py collectstatic --noinput
      python manage.py makemigrations items --no-input
      python manage.py migrate --no-input
      python manage.py create_superuser --no-input
    startCommand: gunicorn inventory_management.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_ALLOWED_HOSTS
        value: data-xlqe.onrender.com,localhost,127.0.0.1
      - key: DJANGO_SETTINGS_MODULE
        value: inventory_management.settings
      - key: DJANGO_SUPERUSER_USERNAME
        value: admin
      - key: DJANGO_SUPERUSER_EMAIL
        value: admin@example.com
      - key: DJANGO_SUPERUSER_PASSWORD
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: mydata-db
          property: connectionString
    autoDeploy: true

databases:
  - name: mydata-db
    plan: free
    databaseName: mydata
    user: mydata_user

