services:
  - type: web
    name: inventory-management
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: gunicorn inventory_management.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_ALLOWED_HOSTS
        value: .onrender.com
      - key: DJANGO_SETTINGS_MODULE
        value: inventory_management.settings
      - key: DATABASE_URL
        fromDatabase:
          name: mydata-db
          property: connectionString
    autoDeploy: true

databases:
  - name: mydata-db
    plan: free
    databaseName: mydata
    user: mydata_user

