# Generated by Django 5.2 on 2025-06-05 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم الصنف')),
                ('barcode', models.CharField(max_length=20, verbose_name='رقم الباركود')),
                ('package', models.CharField(max_length=100, verbose_name='العبوة')),
                ('company', models.CharField(max_length=255, verbose_name='الشركة')),
                ('submitter', models.CharField(max_length=255, verbose_name='المدخل المرسل')),
                ('unit', models.CharField(max_length=100, verbose_name='وحدة الصنف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'صنف',
                'verbose_name_plural': 'أصناف',
                'ordering': ['-created_at'],
            },
        ),
    ]
